name: ci

on:
  push:
    branches:
      - "master"
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push LATEST
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: robsontenorio/laravel

      - name: Build and push TAG:${{ github.event.release.tag_name }}
        uses: docker/build-push-action@v2
        if: github.ref != 'refs/heads/master'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: robsontenorio/laravel:${{ github.event.release.tag_name }}
