version: "3"

volumes:
  {{APP_NAME}}-postgres-volume: null
  {{APP_NAME}}-postgres-test-volume: null  
  {{APP_NAME}}-redis-volume: null
  {{APP_NAME}}-minio-volume: null

services:
  ######## APP ########
  {{APP_NAME}}-app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      target: local
    environment:
      - CONTAINER_ROLE=APP    
      - DEV_MODE=TRUE
    volumes:
      - ../:/var/www/app:cached
    ports:
      - 8017:8080
    depends_on:
      - {{APP_NAME}}-postgres
      - {{APP_NAME}}-redis

  ######## DATABASE ########
  {{APP_NAME}}-postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_DB={{APP_NAME}}
      - POSTGRES_USER={{APP_NAME}}
      - POSTGRES_PASSWORD={{APP_NAME}}      
    volumes:
      - {{APP_NAME}}-postgres-volume:/var/lib/postgresql/data
    ports:
      - 5417:5432

  ######## DATABASE (TEST) ########
  {{APP_NAME}}-postgres-test:
    image: postgres:14.2
    environment:
      - POSTGRES_DB={{APP_NAME}}db
      - POSTGRES_USER={{APP_NAME}}
      - POSTGRES_PASSWORD={{APP_NAME}}
    volumes:
      - {{APP_NAME}}-postgres-test-volume:/var/lib/postgresql/data
    ports:
      - 54170:5432      
    
  ######## REDIS ########
  {{APP_NAME}}-redis:
    image: redis:6.2.4
    volumes:
      - {{APP_NAME}}-redis-volume:/data
    ports:
      - 6317:6379
